### ISSUE TITLE
Cleaning up of UI branch

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#20]
The UI branch need to have only the front-end code. The development branch should be set up such that a simple merge is suffice between UI and backend branches. At all times, the development branch will be a properly functioning application that is a merged result of the latest working commits of the backend and ui branches.

The images stored in the data/img directory of the commit #19 belong to documentation wiki. There is a separate directory for images in the wiki repository. These images can be committed there and a proper wiki page explaining the overall context, user stories etc should be put up in the wiki.

**Comment by sukantoguha** [comment]
Sir , I have shifted all the images to the wiki, including removing the earlier ones. They were six images which Amit had also added to data/img/ which were already present in the wiki img folder, I have removed them too.

**Comment by prasadtalasila** [comment]
There is still the Java code in the ui branch. This code would not let us perform a clean merge of the repos. Please remove all the backend code from ui branch.
Both of you can decide on the merged structure and then post to the corresponding directories in the ui and backend branches. That way a clean merge is possible for the development branch.

**Comment by crygnus** [comment]
I think UI branch is cleaned up now. So we can close this issue.
Just for the record. Creating a UI branch was a pretty bad idea. Creating a UI branch and making a commit of removing all the code **creates a very huge merge conflict** when merging it with backend or development. Git doesn't see merging two branches as merging file from one branch to another. Remember that a commit is **entire snapshot** of repo at that point. Since the snapshot of UI includes _deletion of files_ while snapshots (commits) at other branches don't, there is a merge conflict over keeping/deleting those files.
