### ISSUE TITLE
Dynamic loading of custom analyzers

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#38]
At present, the custom analyzers are generated using P4toJava. After getting the Java files from P4toJava compiler, these packet analyzer itself is compiled, packaged and deployed.

A nice feature would be to dynamically add custom analyzers to a running instance of a packet analyzer. We can probably use [scar](https://github.com/EsotericSoftware/scar) utility for doing this.

Since Java SE 6 version, there has been support for Java compiler API in [Java Tools package](http://docs.oracle.com/javase/6/docs/api/javax/tools/package-summary.html). The class of interest would be [JavaCompiler](http://docs.oracle.com/javase/6/docs/api/javax/tools/JavaCompiler.html).

**Comment by crygnus** [comment]
In my opinion it would be better to implement a plugin approach. By forcing new custom analyzers to behave as plugins, we can control their access to resources like file operations and DB access. Plugin approach is suitable for our application because of two reasons - 
1. If analyzers are implemented as plugins then we can enforce security policies on them which will make it impossible for them to execute any action outside of those policies. (See - [Java Policy](https://docs.oracle.com/javase/7/docs/api/java/security/Policy.html)). This adds to the application security.
2. Analyzers don't need to have disk/DB access anyway. The input parsing is already being performed by core code. Output of analyzers is also not pushed directly to DB but passes through an intermediate layer of optimized DB write code. Thus analyzer behavior is compliant to a plugin definition.

For implementing plugin loading, see - 
1. [Adding Plugins to a Java Application](http://www.javaranch.com/journal/200607/Plugins.html)
2. [Java Plugin Framework](http://jpf.sourceforge.net/)

**Comment by prasadtalasila** [comment]
The relevant project-specific document is available on the [wiki](https://github.com/prasadtalasila/BITS-Darshini/wiki/Security-Model).

**Comment by crygnus** [comment]
So are we going ahead with plugin approach? If it is so then I can start working on the design.

**Comment by prasadtalasila** [comment]
Not a priority right now.
