### ISSUE TITLE
Error in Webapp

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#6]
When the read PCAP option is selected, the following error appears as a result

http://ec2-52-34-103-47.us-west-2.compute.amazonaws.com:8080/protocolanalyzer/reader;jsessionid=E2226309C749B9E588CAA2C930256B77?

**Comment by crygnus** [comment]
Tomcat went down because of insufficient memory. I have stopped some unnecessary processes running. I have also stopped jenkins for now where there are no regular commits to this repo on a daily basis. Jenkins is quite a resource intensive application and since server has only 1 GB ram, I suspect it got overwhelmed.

**Comment by prasadtalasila** [comment]
Increasing the swap space of the VM can take care of the crash problem. You can also allocate minimum guaranteed memory to TomCat so that the web app itself never crashes for the lack of memory.

**Comment by crygnus** [comment]
Adding swap space did not alleviate the problem neither did the JVM arguments about max memory size at tomcat deployment. Though I doubt jenkins is not the culprit. During each new deployment in my local machine, I get following warning from tomcat - 

SEVERE: The web application [/protocolanalyzer] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.

Perhaps that is what is causing the memory leak and could be the reason behind OutOfMemory issue as hinted [here](http://stackoverflow.com/questions/3320400/to-prevent-a-memory-leak-the-jdbc-driver-has-been-forcibly-unregistered).

It doesn't affect running the application on my machine since it has got more resources than my AWS server. I will continue looking deeper.

**Comment by crygnus** [comment]
I have solved two kinds of errors for now - 
1. Out of memory error.
2. Duplicate loading of libraries (.so file) used during reading pcaps files (Especially by jna)

The fix was [this commit](https://github.com/prasadtalasila/PacketAnalyzer/commit/e1416198f8c3113d3e8a175b954795582398d942). After opening the pcap file, it wasn't being closed in the code. I added that line.

Please try hitting the application url (and using the application) after jenkins builds and see if you get any error. If not then please close this issue.

**Comment by crygnus** [comment]
I agree that the application is still using way too much memory than it should. I am still looking into that but that could be tracked as a different issue.

**Comment by prasadtalasila** [comment]
issue #17 has opened for memory profiling.
