### ISSUE TITLE
migrate vagrant box to xenial64

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#64]
When the vagrant box is changed from ubuntu/trusty64 to ubuntu/xenial64, the maven upload to tomcat7 fails with the error of contextpath not being available.

**Comment by prasadtalasila** [comment]
upgrade done in 24394bd commit.

**Comment by SebastinSanty** [comment]
Instead of going with the canonical version of (ubuntu/xenial64) which seems to be not fixing the password issue (and other issues), why not go with (v0rtex/xenial64) as is discussed in this [thread](https://bugs.launchpad.net/cloud-images/+bug/1569237) and [comment #33](https://bugs.launchpad.net/cloud-images/+bug/1569237/comments/33).
