### ISSUE TITLE
Invalid successful shared message 

### ISSUE THREAD

**Issue by prasadtalasila** [prasadtalasila/BITS-Darshini#87]
In the share experiment page, when the user clicks on share drop down, but does not select any users and clicks on share button, a success notification comes.

Success notification should only come when the experiment is shared with at least one other user. Self-sharing (owner sharing an experiment with himself) of an experiment does not make sense.

**Comment by SebastinSanty** [comment]
There is no self-sharing. It has been removed in one of the recent commits. The success notification should be coming but it should be showing 'Successfully shared with None' (at present it just shows 'Successfully shared with'). 

Success notification, because the user should also be given an opportunity to revoke the rights of accessing the experiment.

**Comment by prasadtalasila** [comment]
The phrase "Successfully shared with None" is a paradox. It's better not to show the pop up message when there are no changes in the shared settings.

Since we also use the **share** button to update the list of existing users, it may be better to rename the **share** button as **update**. A semantically consistent interaction would be a change in the list of shared users and then the **update** button becomes active. User clicks on **update** button to update the shared settings in elastic search.

**Comment by prasadtalasila** [comment]
Not a priority right now.
